use PAT

diff --git a/.github/workflows/transfer-issues.yml b/.github/workflows/transfer-issues.yml
--- a/.github/workflows/transfer-issues.yml
+++ b/.github/workflows/transfer-issues.yml
@@ -1,5 +1,18 @@
 name: Transfer issues
 
+# To run this action.
+# 1. Create a personal access token (Classic) with the `repo` and `read:org` scopes.defaults:
+# 2. Create a secret in the repository with whatever name you want, and paste the token as the value.
+# 3. Run the action with the secret name as the `secret_name` input.
+#
+# Ex: gh secret set MY_TOKEN --body "<token_value>" && gh workflow run 90730614 --field count="10" --field from_name="addons-server" --field secret_name="MY_TOKEN"
+#
+# Note: you need to paste the PAT in body, so make sure to keep track of the value before saving it.
+# Also verify the workflow ID is correct. You can run without arguments and select interactively.
+#
+# Note: After each run this action purges the secret from the repo action secrets.
+# This prevents pollution or conflict. So you have to reset it every time.
+
 on:
   workflow_dispatch:
     inputs:
@@ -9,6 +22,9 @@ on:
         required: true
       from_name:
         description: "the name of the mozilla/<from_name repository to transfer issues from"
+        required: true
+      secret_name:
+        description: "the name of the secret containing the PAT for the repository to transfer issues to"
         required: true
 
 permissions: write-all
@@ -25,58 +41,89 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - id: meta
-        if: github.event_name == 'workflow_dispatch'
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        shell: bash
-        run: |
-          if [[ ! "${{ env.ALLOWED_REPOS }}" =~ (^|,)"${{ inputs.from_name }}"(,|$) ]]; then
-            echo "Invalid from_name "${{ inputs.from_name }}". Exiting..."
-            exit 1
-          fi
 
-          echo "from_repo=${{ github.server_url }}/${{ github.repository_owner }}/${{ inputs.from_name }}" >> $GITHUB_OUTPUT
-          echo "to_repo=${{ github.server_url }}/${{ github.repository }}" >> $GITHUB_OUTPUT
-          echo "repo_label=repository:${{ inputs.from_name }}" >> $GITHUB_OUTPUT
-
-      - name: Transfer
-        if: github.event_name == 'workflow_dispatch'
+      - name: Transfer issues
         env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GH_TOKEN: ${{ secrets[format('{0}', inputs.secret_name)] }}
         shell: bash
         run: |
           set -x
 
+          echo "token: $GH_TOKEN"
           gh auth status
+          
+          from_name="${{ inputs.from_name }}"
+          repo_label="repository:$from_name"
+          allowed_repos="${{ env.ALLOWED_REPOS }}"
+          repository_owner="${{ github.repository_owner }}"
+          to_name="${{ github.event.repository.name }}"
+          count="${{ inputs.count }}"
 
-          gh label clone ${{ steps.meta.outputs.from_repo }} -R ${{ steps.meta.outputs.to_repo }} --force
+          if [[ ! "$allowed_repos" =~ (^|,)"$from_name"(,|$) ]]; then
+            echo "Invalid from_name "$from_name". Exiting..."
+            exit 1
+          fi
 
-          gh label create ${{ steps.meta.outputs.repo_label }} -R ${{ steps.meta.outputs.to_repo }} --force
+          echo "Transferring issues from \"$repository_owner/$from_name\" to \"$repository_owner/$to_name\""
 
-          transfer_issue() {
-            original_issue_url=$1
-            from_repo=$2
-            to_repo=$3
-            repo_label=$4
+          repository_id=$(gh repo view "$repository_owner/$to_name" --json id --jq '.id')
 
-            echo "$original_issue_url" >> old-issues.txt
+          issues_query="""
+            query {
+              repository(owner: \"$repository_owner\", name: \"$from_name\") {
+                issues(first: $count, orderBy: {field: CREATED_AT, direction: ASC}) {
+                  nodes {
+                    id
+                  }
+                }
+              }
+            }
+          """
 
-            new_issue_url=$(gh issue transfer -R $from_repo "$original_issue_url" "$to_repo")
+          issues=$(gh api graphql -f query="$issues_query" --jq '.data.repository.issues.nodes[].id')
 
-            echo "$new_issue_url" >> new-issues.txt
+          transfer_mutation="mutation {"
 
-            echo "Transferred issue $original_issue_url to $new_issue_url"
+          new_issues_counter=1
 
-            gh issue -R $to_repo edit $new_issue_url --add-label $repo_label
-          }
+          while IFS= read -r issue_id; do
+            transfer_mutation+=" t${new_issues_counter}: transferIssue(input: { issueId: \"${issue_id}\", repositoryId: \"${repository_id}\", createLabelsIfMissing: true }) { issue { id url } }"
+            new_issues_counter=$((new_issues_counter+1))
+          done <<< "$issues"
 
-          export -f transfer_issue
+          transfer_mutation+=" }"
 
-          echo "Transferring issues from \"${{ steps.meta.outputs.from_repo }}\" to \"${{ steps.meta.outputs.to_repo }}\""
+          new_issues=$(gh api graphql -f query="$transfer_mutation" --jq '.data | keys[] as $k | {url: .[$k].issue.url, id: .[$k].issue.id}')
 
-          gh issue list -R "${{ steps.meta.outputs.from_repo }}" -s all -L ${{ inputs.count}} --json url --search "sort:created-asc" --jq '.[] | .url'| xargs -P 4 -I % bash -c -e 'transfer_issue % '"${{ steps.meta.outputs.from_repo }}"' '"${{ steps.meta.outputs.to_repo }}"' '"${{ steps.meta.outputs.repo_label }}"''
+          new_issue_ids=$(echo "$new_issues" | jq -r '.id')
+          
+          gh label create \"$repo_label\" -R "$repository_owner/$to_name" --force
 
-          cat old-issues.txt
+          label_id=$(gh api /repos/$repository_owner/$to_name/labels/$repo_label --jq '.node_id')
 
-          cat new-issues.txt
+          label_mutation="mutation {"
+
+          label_counter=1
+
+          while IFS= read -r id; do
+            label_mutation+=" l${label_counter}: updateIssue(input: {id: \"$id\", labelIds: [\"$label_id\"]}) { __typename }"
+            label_counter=$((label_counter+1))
+          done <<< "$new_issue_ids"
+
+          label_mutation+=" }"
+
+          gh api graphql -f query="$label_mutation"
+
+          echo "$new_issues" | jq -r '.url'
+
+      - name: Delete secret
+        if: always()
+        shell: bash
+        env:
+          GH_TOKEN: ${{ secrets[format('{0}', inputs.secret_name)] }}
+        run: |
+          set -x
+          if gh secret list --json name --jq '.[] | .name' | grep -q "${{ inputs.secret_name }}"; then
+            gh secret delete ${{ inputs.secret_name }}
+          fi
+          
